language: r

sudo: required

# Install the bleeding edge version of a package from github (eg to pick
# up a not-yet-released bugfix)
r_github_packages:
 - dwinter/rensembl

notifications:
  email:
    on_success: change

after_failure: 
    cat /home/travis/build/rachelss/rrelrates/rrelrates.Rcheck/00install.out
